[build]
  publish = "dist"
  command = "pnpm install && pnpm build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  VITE_SUPABASE_URL = "https://fycrkqrhrxcarllthqfl.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Y3JrcXJocnhjYXJsbHRocWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTg2MDEsImV4cCI6MjA3MzY3NDYwMX0.H_PxPGnsIOWuKNsSPBNKIi4-Nwn_1qqNPfVSRe6w64A"
  VITE_API_BASE_URL = "https://manion-backendver11-production.up.railway.app"
