/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fycrkqrhrxcarllthqfl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Y3JrcXJocnhjYXJsbHRocWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTg2MDEsImV4cCI6MjA3MzY3NDYwMX0.H_PxPGnsIOWuKNsSPBNKIi4-Nwn_1qqNPfVSRe6w64A"